import LocalizedStrings from 'react-native-localization'

export const strings = new LocalizedStrings({
  en: {
    containerLabel: 'Container',
    createMyceliumButton: 'Create mycelium',
    descriptionLabel: 'Species description',
    generationLabel: 'Generation',
    notesLabel: 'Notes',
    prefixLabel: 'Prefix',
    providerLabel: 'Provider',
    quantityLabel: 'Quantity to produce',
    roomLabel: 'Room',
    screenHeader: 'New mycelium',
    shelfTimeLabel: 'Shelf time (days)',
    sourceMycelium: 'Source mycelium',
    sourceType: 'Source type',
    speciesLabel: 'Species',
    stageLabel: 'Type',
    substrateLabel: 'Substrate',
    weightLabel: 'Weight (g)',
  },
  es: {
    containerLabel: 'Contenedor',
    createMyceliumButton: 'Crear micelio',
    descriptionLabel: 'Características de la cepa',
    generationLabel: 'Generación',
    notesLabel: 'Observaciones',
    prefixLabel: 'Prefijo',
    providerLabel: 'Proveedor',
    quantityLabel: 'Cantidad a producir',
    roomLabel: 'Ambiente destino',
    screenHeader: 'Nuevo micelio',
    shelfTimeLabel: 'Tiempo de vida (días)',
    sourceType: 'Tipo de fuente',
    speciesLabel: 'Especie',
    stageLabel: 'Tipo',
    substrateLabel: 'Sustrato',
    weightLabel: 'Peso (g)',
  },
})
